name: havilah docker CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env: 
  IMAGE_NAME: havillahims
  IMAGE_TAG: ${{ github.run_id }}
  DOCKER_REPO_NAME: femicancode
  AZURE_CONTAINER_URL: havillahims.h6dhhyacgsa9aqex.southafricanorth.azurecontainer.io
  AZURE_CONTAINER_DNS_NAME_LABEL: himsurl
  AZURE_CONTAINER_INATANCE_NAME: hims
  AZURE_CONTAINER_INSTANCE_LOCATION: South Africa North
  AZURE_RESOURCE_GROUP: HIMS-RG
  AZURE_SUBSCRIPTIONID: 80e570d4-d806-4879-9214-67ba31976973

jobs:

  build-Frontend-image:
    name: Build HavillahIms Frontend Container Image
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: Havillah

    steps:
    - uses: actions/checkout@v3
    
      #Stage 1: Build
    - name: Build the Docker image
      run: docker build . --file HavillahWebUI_Server/Dockerfile --tag $DOCKER_REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
      
      #Stage 2: Save Image
    - name: save image as Tar
      run: docker save -o ${{ format('{0}/{1}.tar', github.workspace, env.IMAGE_NAME) }} $DOCKER_REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
    
      #Stage 3: Upload to a location
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: HIMSFrontendImage
        path: ${{ format('{0}/{1}.tar', github.workspace, env.IMAGE_NAME) }}
        
  deploy-image:
      name: deploy image
      runs-on: ubuntu-latest
      needs: build-Frontend-image
      environment:
        name: Dev
        
      steps: 
      - name: Download a Build Artifact
        id: downloadImage
        uses: actions/download-artifact@v3.0.2
        with:
          name: HIMSFrontendImage
          
        #Stage 1: Rehydrate the image
      - name: Rehydrate the image
        run: docker load -i ${{ format('{0}/{1}.tar', steps.downloadImage.outputs.download-path, env.IMAGE_NAME) }}
        
        #Stage 2: Login
      - name: DockerHub Login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
          
      - name: Build and Push docker container to registry
        run: docker push ${{ env.DOCKER_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Create aci context
        run:  az container create --resource-group ${{env.AZURE_RESOURCE_GROUP}} --name ${{env.AZURE_CONTAINER_INATANCE_NAME}} --image ${{ env.DOCKER_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --dns-name-label ${{AZURE_CONTAINER_DNS_NAME_LABEL}} --ports 8089
        

  

